name: Build ISO

on:
  workflow_dispatch

jobs:
  build-iso:
    name: Build ISO Installer
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ISO
        id: build
        uses: JasonN3/build-container-installer@main
        with:
          flatpak_remote_refs_dir: flatpak_refs
          image_name: fedora_workstation
          image_repo: ghcr.io/jasonn3
          image_tag: ${{ github.ref_name }}
          version: 40
          variant: Workstation

      - name: Move to save location
        run:
          mv ${{ steps.build.outputs.iso_path }} /save/
